# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a603a7c03092d2643503dc2913fcf352e6cd6798e272458b87fbdae6ceeb0d1e7c7066d13939000fc9a4d6fd180b4d6f2a175cd27cb17bfb0536991b745a4e94

test:
  secret_key_base: 64ec8a1f4e3f007d7d7403e61fbd5bdb12ca5e53a8d873f059a5f032cb980d63c064b2c9a936137a24d4fa4908df16686633955e9f669e637f40cafb9d10b5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
